apiVersion: v1
kind: Service
metadata:
  name: vproapp
  namespace: vprofile
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: alb  
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: vproapp