apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  namespace: vprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      initContainers:
        # Wait for DB
        - name: init-mydb
          image: busybox
          command: ['sh', '-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
        # Wait for Memcached
        - name: init-memcached
          image: busybox
          command: ['sh', '-c', 'until nslookup vpromc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for memcached; sleep 2; done;']
      containers:
        - name: vproapp
          image: rahulsoni07064/vproapp:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "200m"
              memory: "250Mi"
